spring.application.name=meymed
spring.data.mongodb.database=${DB_NAME}
spring.data.mongodb.uri=${DB_URI}
logging.level.org.springframework.web=INFO
logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO
server.port=8080
jwt.secret=${JWT_SECRET}